image: gradle:latest

stages:
  - build

before_script:
  - apt-get update -yqq
  - apt-get install -yqq junit

build_game:
  stage: build
  script:
    - gradle compileJava

test_game:
  stage: test
  script:
    - gradle test